### ISSUE TITLE
Redundancy

### ISSUE THREAD

**Issue by finnoleary** [paulgb/BarbBlock#11]
It would be useful to have several other mirrors of BarbBlock that are upstream of this repo, to ensure a central source of truth in the future if Github decides to take this repository down.

Some alternative sites include gitlab.com and gitgud.io (Both allow you to mirror to Github, Bitbucket, et al. afaik). I understand the point of this is to challenge the DCMA, but while that challenge is in progress this repository will be inaccessible by the public.

**Comment by paulgb** [comment]
I have registered http://bblck.me which will provide some means of failover against a takedown. It won't be automatic, but will point it at another server to keep the blacklist text file working should a takedown occur. It could still be shut down by a court order but that's perfectly fine with me, I just want a workaround to the DMCA loophole where companies can censor projects for 10-14 days for no valid legal reason with basically no recourse.

Do you know where gitgud is hosted?

**Comment by alphapapa** [comment]
@paulgb gitgud.io appears to be run by sapphire.moe, which is run by two guys in the USA.  From reading their blog, their servers appear to be as well.

https://blog.sapphire.moe

**Comment by finnoleary** [comment]
I only really brought up gitgud.io because I had a flag set for "Does not respond to DCMA requests", but, double checking, I was incorrect about that. I'm sure there are foreign instances of git that will not, however.

**Comment by paulgb** [comment]
A user Gunnar is now hosting a mirror in Iceland: https://git.system.is/barbblock/BarbBlock
