### ISSUE TITLE
Secure URL for list

### ISSUE THREAD

**Issue by josephcsible** [paulgb/BarbBlock#12]
The current URL provided for the list, http://bblck.me/BarbBlock.txt, is insecure. Can that domain be made secure, or the URL updated to one that is secure (currently, https://raw.githubusercontent.com/paulgb/BarbBlock/master/BarbBlock.txt seems to work)?

**Comment by paulgb** [comment]
Ah bummer, I thought the CDN-serve HTTPS version of the site (on the github.io domain) would continue to work but it now redirects to the non-HTTPS custom domain.

I think the best way to do this is serve it through a CDN that supports HTTPS, I'll take a look

**Comment by paulgb** [comment]
Done! https://ssl.bblck.me/BarbBlock.txt

I have updated README.md to reflect this as well.
