### ISSUE TITLE
Generate hosts-file style list

### ISSUE THREAD

**Issue by paulgb** [paulgb/BarbBlock#13]
Per @migueldemoura's comment in #5

**Comment by paulgb** [comment]
@migueldemoura how's this:

https://github.com/paulgb/BarbBlock/blob/master/blacklists/hosts-file.txt

**Comment by migueldemoura** [comment]
Not sure if there's an issue with using a tab instead of a space between the ip and hostname, might want to check that.

**Comment by paulgb** [comment]
I think tab is the most compatible, are you having problems with it parsing? May be the comment syntax if so

**Comment by migueldemoura** [comment]
Not at all, it works fine. Feel free to merge it

**Comment by paulgb** [comment]
You can find the hosts file here: `https://ssl.bblck.me/blacklists/hosts-file.txt`

It will remain in sync with the list.
