### ISSUE TITLE
Improve transparency

### ISSUE THREAD

**Issue by devnoname120** [paulgb/BarbBlock#18]
This list is useful in my opinion, as it also acts as a hall of shame for legal intimidators.
Yet, I would like to be able to see which legal threat caused some domain to be added to the list, because it's both informative, and it makes sure that no domain is added here by mistake.

Would it be possible to add as a comment next to each domain entry a link pointing to the legal threat?

**Comment by paulgb** [comment]
Thanks for the feedback, this is definitely something I want to do. I'm working on automatically generating the blacklists from one file, which includes metadata linking them back to the github issue, which will contain details on the takedown that initiated their addition.

**Comment by paulgb** [comment]
This is somewhat in place now, see https://github.com/paulgb/BarbBlock/blob/master/blacklist.json

**Comment by devnoname120** [comment]
Great! Since this is meant to be maintained by hand, I suggest you to use a more human-friendly markup language such as YAML.

**Comment by paulgb** [comment]
Good call, I like yaml. Done.
