### ISSUE TITLE
Filter syntax could potentially cause false positives

### ISSUE THREAD

**Issue by gorhill** [paulgb/BarbBlock#19]
In your README file, you mention that the list can be used as a block list in other blockers:

> **As a blacklist for another blocker**
> 
> Add `https://ssl.bblck.me/BarbBlock.txt` as a blacklist.

Given the syntax you have used (`||example.com`), and the comment character used (`!`), I am going to assume you have in mind blockers such as ABP, uBO, AdGuard, etc.

However the syntax of the filters could lead to false positives. For instance, the first entry:

    ||functionalclam.com

This could cause false positives. Consider this fictitious URL:

    https://functionalclam.com.example.com/index.html

Your filter would be a hit on this URL, while I am sure this is not what you intended.

You need to add the `^` special character at the end of the hostname:

    ||functionalclam.com^

The purpose of `^` is described here: <https://adblockplus.org/filter-cheatsheet#blocking2>:

> A separator character has to follow that will indicate the end of the domain name, e.g. `/` or `:`.

I know a false positive is unlikely with those weird hostnames, but still, a `^` appended at the end would just completely remove the risk.

**Comment by migueldemoura** [comment]
Beat me to it. Absolutely correct

**Comment by paulgb** [comment]
Thanks, this is important to get right!
