### ISSUE TITLE
List fails to download on AdBlock Plus

### ISSUE THREAD

**Issue by srsgores** [paulgb/BarbBlock#25]
On Adblock Plus for Chrome, I encounter the following error when trying to install barblock:

> Failed, download failure

![image](https://user-images.githubusercontent.com/1750837/29482156-1f6f7ee6-8449-11e7-948c-8c88b072087d.png)

**Comment by paulgb** [comment]
I can reproduce this. It looks like it's the `Redirect` header that's causing this to fail. ABP is actually requesting the right URL and getting the right response, but then it sees the redirect header and loads the file again, causing it to get into a redirect loop. After a few redirects it gives up.

This differs from the behavior described in the ABP filter docs [here](https://adblockplus.org/filters#special-comments). Might be an ABP bug. For now the adblock plus list has never moved so I'm not too worried about having the redirect work, so I've simply removed the `Redirect` header from the ABP list.

It will take ~60 minutes to propagate to the CDN, if it still doesn't work after that feel free to comment here / reopen this.
