### ISSUE TITLE
Remove extra spaces in hosts file

### ISSUE THREAD

**Issue by Gitoffthelawn** [paulgb/BarbBlock#26]
In order to facilitate merging with other hosts files, can you please remove the extra spaces in each line from
https://ssl.bblck.me/blacklists/hosts-file.txt

Thanks!

**Comment by paulgb** [comment]
I can do that. Would a tab character work or is a single space character preferable?

**Comment by Gitoffthelawn** [comment]
Thanks.  A single space is preferable.

**Comment by paulgb** [comment]
Done. Should be live within an hour or so.

**Comment by Gitoffthelawn** [comment]
Thank you!
