### ISSUE TITLE
Admiral domain: texturetrick.com

### ISSUE THREAD

**Issue by TatharNuar** [paulgb/BarbBlock#30]
`http://texturetrick.com/`

Found this Admiral domain while browsing https://www.comicsands.com/teens-pretending-lgbtq-scientific-surveys-2623048406.html?utm_content=inf_1123_3759_1&utm_source=twitter&utm_campaign=SAND&tse_id=INF_545f4d90fd9011e8b433ab68d22425b2 and blocked it.

**Comment by TatharNuar** [comment]
I can't seem to add the Blacklist label to this issue.

**Comment by paulgb** [comment]
Thanks, added.
