### ISSUE TITLE
`ssl.bblck.me` is no longer having a valid DNS record.

### ISSUE THREAD

**Issue by IceCodeNew** [paulgb/BarbBlock#34]
`ssl.bblck.me` is no longer having a valid DNS record.

**Comment by paulgb** [comment]
Thanks. The domain has expired. I've updated the instructions accordingly.

**Comment by Gittyperson** [comment]
Could you please also update the extension links [here](https://paulgb.github.io/BarbBlock/install)? Thanks.

**Comment by bug-rules** [comment]
> Could you please also update the extension links here? Thanks.

Fixed.

uBO version also have latest: 

`ubo:subscribe`/`ubo://subscribe` protocol with uBO `v1.16.X`+ 

So that the version list can not work badly with AdBlock / Adblock Plus in the feature.
