### ISSUE TITLE
Add fake AntiVir sites

### ISSUE THREAD

**Issue by juergen852** [paulgb/BarbBlock#44]
Add 
avast-securedownload[.]com
bitdefender-app[.]com
malwarebytes[.]pro

to Blocklist.

Reason: Fake AV Sites
Source: https://www.heise.de/news/Gefaelschte-Antivirus-Webseiten-wollen-Opfern-Malware-unterjubeln-9733022.html

**Comment by paulgb** [comment]
Hi, thanks for submitting, but unless these have used DMCA takedowns to be removed from other lists, they are out of scope for this list.
