### ISSUE TITLE
Create a list instead of a full-blown extension

### ISSUE THREAD

**Issue by migueldemoura** [paulgb/BarbBlock#5]
Title pretty much sums it all - why an extension and not a list? You can advertise uBlock or any other blocker and provide instructions on how to add the list (a simple url like `abp:subscribe?location=` would suffice). This saves resources and follows DRY.

If you're worried about traction, you may ask for it to be included as one of uBlock's default lists. Either way, and given your target audience, I don't believe this to be the best approach.

Good luck! :+1: 

Edit: If you'd like to keep the extension, could you please provide a file with the list of domains as well?

**Comment by collinbarrett** [comment]
Agreed. I would love a standard list version as well. I'd love to be able to include it over on [FilterLists](https://github.com/collinbarrett/FilterLists/issues/108). It's a great idea!

**Comment by niladam** [comment]
I agree this is a better way. It'll allow for easier adoption and also easier maintenance.

**Comment by Spacial** [comment]
maybe a centralized list from/to pihole, ublock, umatrix, etc..?

**Comment by migueldemoura** [comment]
Both uBlock and uMatrix support hosts-like filter lists. In the case of uBlock, `0.0.0.0 example.com` is translated to `||example.com^`. Other blockers should support these as well (and they would obviously work when appended to `/etc/hosts`).

**Comment by Dynalon** [comment]
Far more sane to create a custom list that is hosted outside the US, where DMCA takedowns can safely be ignored. Users just can use existing adblock/ublock and add that list.

Hosting a new extension on github - which forwarded the DMCA takedown notice to the repository owner - is especially nonsense.

**Comment by getaaron** [comment]
I agree with @Dynalon. I think it would be trivial to create a few automatic repo mirrors too.

**Comment by paulgb** [comment]
Thanks, I'll look into what format works. Do most ad blockers allow you to point them to a URL to periodically fetch the list from, so that it can update automatically? Or does it have to be submitted to an "app store" of sorts for each blocker?

> Hosting a new extension on github - which forwarded the DMCA takedown notice to the repository owner - is especially nonsense.

The point here is to not cede territory here by switching to a technologically harder to block solution. What Admiral are doing is an abuse of the legal process and if I meet resistance I'd rather face it head on.

**Comment by migueldemoura** [comment]
@paulgb, only a URL is needed. The blocker automatically fetches updates to the list and most also allow you to specify the update interval. For additional guidance, take a look at https://adblockplus.org/filters.

**Comment by paulgb** [comment]
Oh great, that sounds very do-able. I'll set it up this weekend once I have
a chance.

**Comment by sangohan** [comment]
>hosted outside the US, where DMCA takedowns can safely be ignored.

i think that has the bad side effect of not disputing invalid DMCA takedowns. Instead, we ought to be fighting these invalid DMCA takedowns, and increase the cost of making a false claim. In aggregate, it will make DMCA less abusable, but will require a tough fight. Making bad press for companies that make false claims won't hurt either. 

Moving information to outside the US juristiction will only allow abusers to continue to harass those who can't move out.

**Comment by getaaron** [comment]
I retract my previous opinion and agree with @paulgb and @sangohan.

**Comment by rodalpho** [comment]
I just came here to suggest this. There's no reason to implement it as a whole new addon when all the adblocking extensions support standard lists.

**Comment by seb-1204** [comment]
I also came here to say I'd like to pull the list into my [Pi-hole](https://github.com/pi-hole/pi-hole) or [uBlock Origin](https://github.com/gorhill/uBlock).

**Comment by niladam** [comment]
Well, hosting it OUTSIDE US *TOO* sounds like a good idea. This way -- in case anything happens with the US/Git one -- you have a fallback to rely upon ?

**Comment by Zhangsun321** [comment]
agreed
make a list
lets see a simple way to track it... i can spam the hell out of it on reddit and twitter :)

**Comment by collinbarrett** [comment]
For anyone who missed #10, there is now, at least temporarily, a subscription list for uBlock, Adblock Plus, etc. [here](https://github.com/paulgb/BarbBlock/blob/master/BarbBlock.txt).

**Comment by paulgb** [comment]
@seb-1204 is this in the format you need? http://bblck.me/BarbBlock.txt

@niladam one of my goals here is to demonstrate that these takedowns are invalid and technology/jurisdiction workarounds are not necessary. *However*, an unfortunate part of the DMCA is that even if a valid counter-takedown is sent immediately after a takedown is enacted the repo could be taken out for 10-14 days even with an invalid takedown. As such, I've registered bblck.me through a non-US registrar. Currently it points to the US-hosted GitHub pages, but if necessary I could redirect it to a non-US server for the 10-14 day DMCA waiting period.

@Zhangsun321 I don't want this to become known as a spammy project, but as long as you mean "spam" in a hyperbolic way, I appreciate your zeal :)!

**Comment by migueldemoura** [comment]
@paulgb, I'd use the hosts format as seen at https://github.com/paulgb/BarbBlock/issues/5#issuecomment-322002902 (`0.0.0.0 example.com`)

**Comment by paulgb** [comment]
Per #12 a better (HTTPS) URL for the list is `https://ssl.bblck.me/BarbBlock.txt`

@migueldemoura Great, I will produce one when I switch the individually-maintained lists into lists generated from a central file later today.
