### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by jeroenhd** [paulgb/BarbBlock#9]
First of all, great work. You have implemented the extension I was thinking to make. Saves most of a lot of work!

As you might know, Firefox now also supports the use of the [WebExtensions](https://developer.mozilla.org/nl/Add-ons/WebExtensions) API. This means that this Chrome addon should be portable to Firefox without much effort. [In fact, I don't see any reasons why this extension wouldn't work on Firefox](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities).

Of course use Firefox users could download the code and install it as an unsigned extension, but then we wouldn't have any convenient way to update the extension in case more producers or websites start abusing DMCA for their shady business practices.

Will you please consider making and publishing a Firefox version of this extension? Your efforts would be greatly appreciated.

**Comment by paulgb** [comment]
Thanks! I've submitted the application for review and will update the status in this issue.

**Comment by tuespetre** [comment]
My first thought when I saw this was "WebExtensions?" so this is good to see. Instead of making a new issue I thought I would just comment here to thank you @paulgb!

**Comment by rctgamer3** [comment]
Approved.

**Comment by slester** [comment]
A link for convenience: https://addons.mozilla.org/en-US/firefox/addon/barbblock/

**Comment by aaron-em** [comment]
If you'd rather not install an extension just for this, you can subscribe your already installed adblocker to the filter list with [the raw URL](https://raw.githubusercontent.com/paulgb/BarbBlock/master/BarbBlock.txt). WFM in uBlock Origin, should work in Adblock Plus if anyone still uses that.

**Comment by paulgb** [comment]
I just created a better raw URL to use: `http://bblck.me/BarbBlock.txt`. It points to the same file, but is served through GitHub's CDN, and if a takedown happens I can point it at another server to avoid a prolonged service disruption.
